select * from df ;
-- total purchase amount 
select 'total purchase amount',
FORMAT(SUM(CAST(`Total Purchase Amount` AS DECIMAL(15,2))), 0) AS Total_Sales
from df;
-- Q1. What is the total revenue generated by male vs. female customers?
select gender,
FORMAT(SUM(CAST(`Total Purchase Amount` AS DECIMAL(15,2))), 0) AS Total_Sales
from df
group by gender;

-- tottal number of returns by each product catagory?return rate in %?
SELECT
    `Product Category`,
    SUM(Returns) AS Total_Returns,
    COUNT(*) AS Total_Transactions,
    ROUND(SUM(Returns) * 100.0 / COUNT(*), 2) AS Return_Rate_Percent
FROM df
GROUP BY `Product Category`
ORDER BY Return_Rate_Percent DESC;

-- which product catagory genrate most revenue
SELECT
    `Product Category`,
    SUM(CAST(`Total Purchase Amount` AS DECIMAL(15,2))) AS Total_Revenue
FROM df
GROUP BY `Product Category`
ORDER BY Total_Revenue DESC;
-- Average order value
SELECT
    ROUND(
        SUM(CAST(`Total Purchase Amount` AS DECIMAL(15,2))) / COUNT(*),2) AS Average_Order_Value
FROM df;
-- payment method is mostly uesd
SELECT
    `Payment Method`,
    COUNT(*) AS Number_of_Transactions
FROM df
GROUP BY `Payment Method`
ORDER BY Number_of_Transactions DESC
LIMIT 4;
-- which month has the highest sales??
SELECT
    MONTHNAME(`Purchase Date`) AS Month_Name,
    SUM(`Total Purchase Amount`) AS Total_Sales
FROM df
GROUP BY MONTH(`Purchase Date`), MONTHNAME(`Purchase Date`)
ORDER BY Total_Sales DESC;

-- which factors are associate with higher spending 
 -- spending by gender
SELECT
    Gender,
    ROUND(AVG(`Total Purchase Amount`), 2) AS Average_Spending
FROM df
GROUP BY Gender
ORDER BY Average_Spending DESC;
-- spending y age
SELECT
    `age_group`,
    ROUND(AVG(`Total Purchase Amount`), 2) AS Average_Spending
FROM df
GROUP BY `age_group`
ORDER BY Average_Spending DESC;
-- Spending by product category
SELECT
    `Product Category`,
    ROUND(AVG(`Total Purchase Amount`), 2) AS Average_Spending
FROM df
GROUP BY `Product Category`
ORDER BY Average_Spending DESC;

-- Spending by payment method
SELECT
    `Payment Method`,
    ROUND(AVG(`Total Purchase Amount`), 2) AS Average_Spending
FROM df
GROUP BY `Payment Method`
ORDER BY Average_Spending DESC;
-- churn rate
SELECT
    ROUND(SUM(Churn) * 100.0 / COUNT(*), 2) AS Churn_Rate_Percent
FROM df;